name: Build Kernel

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
         
      - name: Setup packages
        run: |
          sudo apt-get update -y
          sudo apt-get -y install repo bc bison build-essential curl ccache coreutils flex g++-multilib gcc-multilib git gnupg \
          gperf libxml2 lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev imagemagick lunzip lzop schedtool squashfs-tools xsltproc zip \
          zlib1g-dev perl xmlstarlet virtualenv xz-utils rr jq libncurses5 pngcrush lib32ncurses5-dev git-lfs libxml2 openjdk-11-jdk wget lib32readline-dev \
          libssl-dev libxml2-utils android-sdk-libsparse-utils lld zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
          lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig ca-certificates bc cpio imagemagick \
          bsdmainutils lz4 aria2 rclone ssh-client libncurses5 libssl-dev rsync schedtool python-is-python3 libarchive-tools python3 zstd

      - name: Set swap to 10G
        uses: pierotofy/set-swap-space@master
        with:
           swap-size-gb: 10

      - name: Clone kernel repo
        run: |
          git clone https://github.com/Burhanverse/kerneltree.git -b 14 --depth=500 kernel
          cd kernel 
          sed -i 's/^CONFIG_LOCALVERSION=".*"/CONFIG_LOCALVERSION="-BlackSapphire"/' arch/arm64/configs/lancelot_defconfig

      - name: Build
        run: |
          cd kernel
          wget https://raw.githubusercontent.com/Burhanverse/build-kernel-circleci/master/config.env
          wget https://raw.githubusercontent.com/Burhanverse/build-kernel-circleci/master/kranul-build.sh && chmod +x ./kranul-build.sh
          echo "Building kernel"
          ./kranul-build.sh

      - name: Download pdup
        run: |
          cd kernel
          wget https://raw.githubusercontent.com/As9124k82134/pdup/master/pdup && chmod +x pdup

      - name: Run pdup
        run: |
          cd kernel
          ./pdup builds/*.zip

      - name: Get upload URL
        id: get_upload_url
        run: |
          echo "::set-output name=url::$(cat upload_output.txt)"

      - name: Download and Release
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: builds
        env:
          RELEASE_URL: ${{ steps.get_upload_url.outputs.url }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            Your file URL: ${{ env.RELEASE_URL }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: builds/*.zip
          asset_name: file.zip
          asset_content_type: application/zip
